package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbBairro generated by hbm2java
 */
public class TbBairro  implements java.io.Serializable {


     private Integer baiId;
     private String baiDescricao;
     private Set tbEndPostals = new HashSet(0);

    public TbBairro() {
    }

    public TbBairro(String baiDescricao, Set tbEndPostals) {
       this.baiDescricao = baiDescricao;
       this.tbEndPostals = tbEndPostals;
    }
   
    public Integer getBaiId() {
        return this.baiId;
    }
    
    public void setBaiId(Integer baiId) {
        this.baiId = baiId;
    }
    public String getBaiDescricao() {
        return this.baiDescricao;
    }
    
    public void setBaiDescricao(String baiDescricao) {
        this.baiDescricao = baiDescricao;
    }
    public Set getTbEndPostals() {
        return this.tbEndPostals;
    }
    
    public void setTbEndPostals(Set tbEndPostals) {
        this.tbEndPostals = tbEndPostals;
    }




}


