package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbCargo generated by hbm2java
 */
public class TbCargo  implements java.io.Serializable {


     private int carId;
     private String carDescricao;
     private double carSalarioBase;
     private Set tbFuncionarios = new HashSet(0);

    public TbCargo() {
    }

	
    public TbCargo(int carId, String carDescricao, double carSalarioBase) {
        this.carId = carId;
        this.carDescricao = carDescricao;
        this.carSalarioBase = carSalarioBase;
    }
    public TbCargo(int carId, String carDescricao, double carSalarioBase, Set tbFuncionarios) {
       this.carId = carId;
       this.carDescricao = carDescricao;
       this.carSalarioBase = carSalarioBase;
       this.tbFuncionarios = tbFuncionarios;
    }
   
    public int getCarId() {
        return this.carId;
    }
    
    public void setCarId(int carId) {
        this.carId = carId;
    }
    public String getCarDescricao() {
        return this.carDescricao;
    }
    
    public void setCarDescricao(String carDescricao) {
        this.carDescricao = carDescricao;
    }
    public double getCarSalarioBase() {
        return this.carSalarioBase;
    }
    
    public void setCarSalarioBase(double carSalarioBase) {
        this.carSalarioBase = carSalarioBase;
    }
    public Set getTbFuncionarios() {
        return this.tbFuncionarios;
    }
    
    public void setTbFuncionarios(Set tbFuncionarios) {
        this.tbFuncionarios = tbFuncionarios;
    }




}


