package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbCidEst generated by hbm2java
 */
public class TbCidEst  implements java.io.Serializable {


     private Integer cepId;
     private TbCidade tbCidade;
     private TbEstado tbEstado;
     private Set tbEndPostals = new HashSet(0);

    public TbCidEst() {
    }

	
    public TbCidEst(TbCidade tbCidade, TbEstado tbEstado) {
        this.tbCidade = tbCidade;
        this.tbEstado = tbEstado;
    }
    public TbCidEst(TbCidade tbCidade, TbEstado tbEstado, Set tbEndPostals) {
       this.tbCidade = tbCidade;
       this.tbEstado = tbEstado;
       this.tbEndPostals = tbEndPostals;
    }
   
    public Integer getCepId() {
        return this.cepId;
    }
    
    public void setCepId(Integer cepId) {
        this.cepId = cepId;
    }
    public TbCidade getTbCidade() {
        return this.tbCidade;
    }
    
    public void setTbCidade(TbCidade tbCidade) {
        this.tbCidade = tbCidade;
    }
    public TbEstado getTbEstado() {
        return this.tbEstado;
    }
    
    public void setTbEstado(TbEstado tbEstado) {
        this.tbEstado = tbEstado;
    }
    public Set getTbEndPostals() {
        return this.tbEndPostals;
    }
    
    public void setTbEndPostals(Set tbEndPostals) {
        this.tbEndPostals = tbEndPostals;
    }




}


