package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbEndereco generated by hbm2java
 */
public class TbEndereco  implements java.io.Serializable {


     private Integer endId;
     private TbEndPostal tbEndPostal;
     private String endNumero;
     private String endComplemento;
     private Set tbEntidades = new HashSet(0);

    public TbEndereco() {
    }

	
    public TbEndereco(TbEndPostal tbEndPostal, String endNumero) {
        this.tbEndPostal = tbEndPostal;
        this.endNumero = endNumero;
    }
    public TbEndereco(TbEndPostal tbEndPostal, String endNumero, String endComplemento, Set tbEntidades) {
       this.tbEndPostal = tbEndPostal;
       this.endNumero = endNumero;
       this.endComplemento = endComplemento;
       this.tbEntidades = tbEntidades;
    }
   
    public Integer getEndId() {
        return this.endId;
    }
    
    public void setEndId(Integer endId) {
        this.endId = endId;
    }
    public TbEndPostal getTbEndPostal() {
        return this.tbEndPostal;
    }
    
    public void setTbEndPostal(TbEndPostal tbEndPostal) {
        this.tbEndPostal = tbEndPostal;
    }
    public String getEndNumero() {
        return this.endNumero;
    }
    
    public void setEndNumero(String endNumero) {
        this.endNumero = endNumero;
    }
    public String getEndComplemento() {
        return this.endComplemento;
    }
    
    public void setEndComplemento(String endComplemento) {
        this.endComplemento = endComplemento;
    }
    public Set getTbEntidades() {
        return this.tbEntidades;
    }
    
    public void setTbEntidades(Set tbEntidades) {
        this.tbEntidades = tbEntidades;
    }




}


