package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbEndPostal generated by hbm2java
 */
public class TbEndPostal  implements java.io.Serializable {


     private Integer endPId;
     private TbLogradouro tbLogradouro;
     private TbBairro tbBairro;
     private TbCidEst tbCidEst;
     private String endPNomerua;
     private String endPCep;
     private Set tbEnderecos = new HashSet(0);

    public TbEndPostal() {
    }

	
    public TbEndPostal(TbLogradouro tbLogradouro, TbBairro tbBairro, TbCidEst tbCidEst, String endPNomerua, String endPCep) {
        this.tbLogradouro = tbLogradouro;
        this.tbBairro = tbBairro;
        this.tbCidEst = tbCidEst;
        this.endPNomerua = endPNomerua;
        this.endPCep = endPCep;
    }
    public TbEndPostal(TbLogradouro tbLogradouro, TbBairro tbBairro, TbCidEst tbCidEst, String endPNomerua, String endPCep, Set tbEnderecos) {
       this.tbLogradouro = tbLogradouro;
       this.tbBairro = tbBairro;
       this.tbCidEst = tbCidEst;
       this.endPNomerua = endPNomerua;
       this.endPCep = endPCep;
       this.tbEnderecos = tbEnderecos;
    }
   
    public Integer getEndPId() {
        return this.endPId;
    }
    
    public void setEndPId(Integer endPId) {
        this.endPId = endPId;
    }
    public TbLogradouro getTbLogradouro() {
        return this.tbLogradouro;
    }
    
    public void setTbLogradouro(TbLogradouro tbLogradouro) {
        this.tbLogradouro = tbLogradouro;
    }
    public TbBairro getTbBairro() {
        return this.tbBairro;
    }
    
    public void setTbBairro(TbBairro tbBairro) {
        this.tbBairro = tbBairro;
    }
    public TbCidEst getTbCidEst() {
        return this.tbCidEst;
    }
    
    public void setTbCidEst(TbCidEst tbCidEst) {
        this.tbCidEst = tbCidEst;
    }
    public String getEndPNomerua() {
        return this.endPNomerua;
    }
    
    public void setEndPNomerua(String endPNomerua) {
        this.endPNomerua = endPNomerua;
    }
    public String getEndPCep() {
        return this.endPCep;
    }
    
    public void setEndPCep(String endPCep) {
        this.endPCep = endPCep;
    }
    public Set getTbEnderecos() {
        return this.tbEnderecos;
    }
    
    public void setTbEnderecos(Set tbEnderecos) {
        this.tbEnderecos = tbEnderecos;
    }




}


