package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbEntidade generated by hbm2java
 */
public class TbEntidade  implements java.io.Serializable {


     private String entCpfCnpj;
     private TbEndereco tbEndereco;
     private String entNome;
     private String entNomeFantasia;
     private String entRgIe;
     private String entFone;
     private String entEmail;
     private String entSexo;
     private Date entDtNasc;
     private String entTipo;
     private Set tbFuncionarios = new HashSet(0);
     private Set tbFornecedors = new HashSet(0);
     private Set tbClientes = new HashSet(0);

    public TbEntidade() {
    }

	
    public TbEntidade(String entCpfCnpj, TbEndereco tbEndereco, String entNome, String entNomeFantasia, String entRgIe, String entFone, String entEmail, String entTipo) {
        this.entCpfCnpj = entCpfCnpj;
        this.tbEndereco = tbEndereco;
        this.entNome = entNome;
        this.entNomeFantasia = entNomeFantasia;
        this.entRgIe = entRgIe;
        this.entFone = entFone;
        this.entEmail = entEmail;
        this.entTipo = entTipo;
    }
    public TbEntidade(String entCpfCnpj, TbEndereco tbEndereco, String entNome, String entNomeFantasia, String entRgIe, String entFone, String entEmail, String entSexo, Date entDtNasc, String entTipo, Set tbFuncionarios, Set tbFornecedors, Set tbClientes) {
       this.entCpfCnpj = entCpfCnpj;
       this.tbEndereco = tbEndereco;
       this.entNome = entNome;
       this.entNomeFantasia = entNomeFantasia;
       this.entRgIe = entRgIe;
       this.entFone = entFone;
       this.entEmail = entEmail;
       this.entSexo = entSexo;
       this.entDtNasc = entDtNasc;
       this.entTipo = entTipo;
       this.tbFuncionarios = tbFuncionarios;
       this.tbFornecedors = tbFornecedors;
       this.tbClientes = tbClientes;
    }
   
    public String getEntCpfCnpj() {
        return this.entCpfCnpj;
    }
    
    public void setEntCpfCnpj(String entCpfCnpj) {
        this.entCpfCnpj = entCpfCnpj;
    }
    public TbEndereco getTbEndereco() {
        return this.tbEndereco;
    }
    
    public void setTbEndereco(TbEndereco tbEndereco) {
        this.tbEndereco = tbEndereco;
    }
    public String getEntNome() {
        return this.entNome;
    }
    
    public void setEntNome(String entNome) {
        this.entNome = entNome;
    }
    public String getEntNomeFantasia() {
        return this.entNomeFantasia;
    }
    
    public void setEntNomeFantasia(String entNomeFantasia) {
        this.entNomeFantasia = entNomeFantasia;
    }
    public String getEntRgIe() {
        return this.entRgIe;
    }
    
    public void setEntRgIe(String entRgIe) {
        this.entRgIe = entRgIe;
    }
    public String getEntFone() {
        return this.entFone;
    }
    
    public void setEntFone(String entFone) {
        this.entFone = entFone;
    }
    public String getEntEmail() {
        return this.entEmail;
    }
    
    public void setEntEmail(String entEmail) {
        this.entEmail = entEmail;
    }
    public String getEntSexo() {
        return this.entSexo;
    }
    
    public void setEntSexo(String entSexo) {
        this.entSexo = entSexo;
    }
    public Date getEntDtNasc() {
        return this.entDtNasc;
    }
    
    public void setEntDtNasc(Date entDtNasc) {
        this.entDtNasc = entDtNasc;
    }
    public String getEntTipo() {
        return this.entTipo;
    }
    
    public void setEntTipo(String entTipo) {
        this.entTipo = entTipo;
    }
    public Set getTbFuncionarios() {
        return this.tbFuncionarios;
    }
    
    public void setTbFuncionarios(Set tbFuncionarios) {
        this.tbFuncionarios = tbFuncionarios;
    }
    public Set getTbFornecedors() {
        return this.tbFornecedors;
    }
    
    public void setTbFornecedors(Set tbFornecedors) {
        this.tbFornecedors = tbFornecedors;
    }
    public Set getTbClientes() {
        return this.tbClientes;
    }
    
    public void setTbClientes(Set tbClientes) {
        this.tbClientes = tbClientes;
    }




}


