package BancoDeDados;
// Generated 09/06/2023 14:46:48 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * TbEstoque generated by hbm2java
 */
public class TbEstoque implements java.io.Serializable {

    private Integer estoId;
    private TbFornecedorHasPeca tbFornecedorHasPeca;
    private float estoQuantidade;
    private float estoValorUni;
    private float estoMargeLucro;
    private String estoMedida;
    private Set tbVenPecas = new HashSet(0);

    public TbEstoque() {
    }

    public TbEstoque(TbFornecedorHasPeca tbFornecedorHasPeca, float estoQuantidade, float estoValorUni, int estoFpId, float estoMargeLucro) {
        this.tbFornecedorHasPeca = tbFornecedorHasPeca;
        this.estoQuantidade = estoQuantidade;
        this.estoValorUni = estoValorUni;
        this.estoMargeLucro = estoMargeLucro;
    }

    public TbEstoque(TbFornecedorHasPeca tbFornecedorHasPeca, float estoQuantidade, float estoValorUni, String estoMedida, Set tbVenPecas, float estoMargeLucro) {
        this.tbFornecedorHasPeca = tbFornecedorHasPeca;
        this.estoQuantidade = estoQuantidade;
        this.estoValorUni = estoValorUni;
        this.tbVenPecas = tbVenPecas;
        this.estoMedida = estoMedida;
        this.estoMargeLucro = estoMargeLucro;
    }

    public Integer getEstoId() {
        return this.estoId;
    }

    public void setEstoId(Integer estoId) {
        this.estoId = estoId;
    }

    public float getEstoMargeLucro() {
        return estoMargeLucro;
    }

    public void setEstoMargeLucro(float estoMargeLucro) {
        this.estoMargeLucro = estoMargeLucro;
    }

    public float getEstoQuantidade() {
        return this.estoQuantidade;
    }

    public void setEstoQuantidade(float estoQuantidade) {
        this.estoQuantidade = estoQuantidade;
    }

    public float getEstoValorUni() {
        return this.estoValorUni;
    }

    public void setEstoValorUni(float estoValorUni) {
        this.estoValorUni = estoValorUni;
    }

    public String getEstoMedida() {
        return this.estoMedida;
    }

    public void setEstoMedida(String estoMedida) {
        this.estoMedida = estoMedida;
    }

    public TbFornecedorHasPeca getTbFornecedorHasPeca() {
        return tbFornecedorHasPeca;
    }

    public void setTbFornecedorHasPeca(TbFornecedorHasPeca tbFornecedorHasPeca) {
        this.tbFornecedorHasPeca = tbFornecedorHasPeca;
    }

    public Set getTbVenPecas() {
        return tbVenPecas;
    }

    public void setTbVenPecas(Set tbVenPecas) {
        this.tbVenPecas = tbVenPecas;
    }

}
