package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbEstado generated by hbm2java
 */
public class TbEstado  implements java.io.Serializable {


     private String estSigla;
     private String estDescricao;
     private Set tbCidEsts = new HashSet(0);

    public TbEstado() {
    }

	
    public TbEstado(String estSigla, String estDescricao) {
        this.estSigla = estSigla;
        this.estDescricao = estDescricao;
    }
    public TbEstado(String estSigla, String estDescricao, Set tbCidEsts) {
       this.estSigla = estSigla;
       this.estDescricao = estDescricao;
       this.tbCidEsts = tbCidEsts;
    }
   
    public String getEstSigla() {
        return this.estSigla;
    }
    
    public void setEstSigla(String estSigla) {
        this.estSigla = estSigla;
    }
    public String getEstDescricao() {
        return this.estDescricao;
    }
    
    public void setEstDescricao(String estDescricao) {
        this.estDescricao = estDescricao;
    }
    public Set getTbCidEsts() {
        return this.tbCidEsts;
    }
    
    public void setTbCidEsts(Set tbCidEsts) {
        this.tbCidEsts = tbCidEsts;
    }




}


