package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbFornecedor generated by hbm2java
 */
public class TbFornecedor  implements java.io.Serializable {


     private Integer forId;
     private TbEntidade tbEntidade;
     private Set tbFornecedorHasPecas = new HashSet(0);

    public TbFornecedor() {
    }

	
    public TbFornecedor(TbEntidade tbEntidade) {
        this.tbEntidade = tbEntidade;
    }
    public TbFornecedor(TbEntidade tbEntidade, Set tbFornecedorHasPecas) {
       this.tbEntidade = tbEntidade;
       this.tbFornecedorHasPecas = tbFornecedorHasPecas;
    }
   
    public Integer getForId() {
        return this.forId;
    }
    
    public void setForId(Integer forId) {
        this.forId = forId;
    }
    public TbEntidade getTbEntidade() {
        return this.tbEntidade;
    }
    
    public void setTbEntidade(TbEntidade tbEntidade) {
        this.tbEntidade = tbEntidade;
    }
    public Set getTbFornecedorHasPecas() {
        return this.tbFornecedorHasPecas;
    }
    
    public void setTbFornecedorHasPecas(Set tbFornecedorHasPecas) {
        this.tbFornecedorHasPecas = tbFornecedorHasPecas;
    }




}


