package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0



/**
 * TbFuncionario generated by hbm2java
 */
public class TbFuncionario  implements java.io.Serializable {


     private Integer funcId;
     private TbCargo tbCargo;
     private TbEntidade tbEntidade;
     private String funcUsuario;
     private String funcSenha;

    public TbFuncionario() {
    }

    public TbFuncionario(TbCargo tbCargo, TbEntidade tbEntidade, String funcUsuario, String funcSenha) {
       this.tbCargo = tbCargo;
       this.tbEntidade = tbEntidade;
       this.funcUsuario = funcUsuario;
       this.funcSenha = funcSenha;
    }
   
    public Integer getFuncId() {
        return this.funcId;
    }
    
    public void setFuncId(Integer funcId) {
        this.funcId = funcId;
    }
    public TbCargo getTbCargo() {
        return this.tbCargo;
    }
    
    public void setTbCargo(TbCargo tbCargo) {
        this.tbCargo = tbCargo;
    }
    public TbEntidade getTbEntidade() {
        return this.tbEntidade;
    }
    
    public void setTbEntidade(TbEntidade tbEntidade) {
        this.tbEntidade = tbEntidade;
    }
    public String getFuncUsuario() {
        return this.funcUsuario;
    }
    
    public void setFuncUsuario(String funcUsuario) {
        this.funcUsuario = funcUsuario;
    }
    public String getFuncSenha() {
        return this.funcSenha;
    }
    
    public void setFuncSenha(String funcSenha) {
        this.funcSenha = funcSenha;
    }




}


