package BancoDeDados;
// Generated 02/06/2023 13:27:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbPagamento generated by hbm2java
 */
public class TbPagamento  implements java.io.Serializable {


     private Integer pagCod;
     private String pagDescricao;
     private Set tbAluguels = new HashSet(0);
     private Set tbVendas = new HashSet(0);

    public TbPagamento() {
    }

	
    public TbPagamento(String pagDescricao) {
        this.pagDescricao = pagDescricao;
    }
    public TbPagamento(String pagDescricao, Set tbAluguels, Set tbVendas) {
       this.pagDescricao = pagDescricao;
       this.tbAluguels = tbAluguels;
       this.tbVendas = tbVendas;
    }
   
    public Integer getPagCod() {
        return this.pagCod;
    }
    
    public void setPagCod(Integer pagCod) {
        this.pagCod = pagCod;
    }
    public String getPagDescricao() {
        return this.pagDescricao;
    }
    
    public void setPagDescricao(String pagDescricao) {
        this.pagDescricao = pagDescricao;
    }
    public Set getTbAluguels() {
        return this.tbAluguels;
    }
    
    public void setTbAluguels(Set tbAluguels) {
        this.tbAluguels = tbAluguels;
    }
    public Set getTbVendas() {
        return this.tbVendas;
    }
    
    public void setTbVendas(Set tbVendas) {
        this.tbVendas = tbVendas;
    }




}


