package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0



/**
 * TbVenPeca generated by hbm2java
 */
public class TbVenPeca  implements java.io.Serializable {


     private Integer vpId;
     private TbVenda tbVenda;
     private TbEstoque tbEstoque;
     private int vpQuantidade;

    public TbVenPeca() {
    }

    public TbVenPeca(TbVenda tbVenda, TbEstoque tbEstoque, int vpQuantidade) {
       this.tbVenda = tbVenda;
       this.tbEstoque = tbEstoque;
       this.vpQuantidade = vpQuantidade;
    }
   
    public Integer getVpId() {
        return this.vpId;
    }
    
    public void setVpId(Integer vpId) {
        this.vpId = vpId;
    }
    public TbVenda getTbVenda() {
        return this.tbVenda;
    }
    
    public void setTbVenda(TbVenda tbVenda) {
        this.tbVenda = tbVenda;
    }
    public TbEstoque getTbEstoque() {
        return this.tbEstoque;
    }
    
    public void setTbEstoque(TbEstoque tbEstoque) {
        this.tbEstoque = tbEstoque;
    }
    public int getVpQuantidade() {
        return this.vpQuantidade;
    }
    
    public void setVpQuantidade(int vpQuantidade) {
        this.vpQuantidade = vpQuantidade;
    }




}


