package BancoDeDados;
// Generated 06/06/2023 20:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TbVeiculo generated by hbm2java
 */
public class TbVeiculo  implements java.io.Serializable {


     private Integer veiId;
     private String veiModelo;
     private String veiMarca;
     private String veiPlaca;
     private Integer veiEmpId;
     private Integer veiPesId;
     private Set tbVendaSers = new HashSet(0);

    public TbVeiculo() {
    }

	
    public TbVeiculo(String veiModelo, String veiMarca, String veiPlaca) {
        this.veiModelo = veiModelo;
        this.veiMarca = veiMarca;
        this.veiPlaca = veiPlaca;
    }
    public TbVeiculo(String veiModelo, String veiMarca, String veiPlaca, Integer veiEmpId, Integer veiPesId, Set tbVendaSers) {
       this.veiModelo = veiModelo;
       this.veiMarca = veiMarca;
       this.veiPlaca = veiPlaca;
       this.veiEmpId = veiEmpId;
       this.veiPesId = veiPesId;
       this.tbVendaSers = tbVendaSers;
    }
   
    public Integer getVeiId() {
        return this.veiId;
    }
    
    public void setVeiId(Integer veiId) {
        this.veiId = veiId;
    }
    public String getVeiModelo() {
        return this.veiModelo;
    }
    
    public void setVeiModelo(String veiModelo) {
        this.veiModelo = veiModelo;
    }
    public String getVeiMarca() {
        return this.veiMarca;
    }
    
    public void setVeiMarca(String veiMarca) {
        this.veiMarca = veiMarca;
    }
    public String getVeiPlaca() {
        return this.veiPlaca;
    }
    
    public void setVeiPlaca(String veiPlaca) {
        this.veiPlaca = veiPlaca;
    }
    public Integer getVeiEmpId() {
        return this.veiEmpId;
    }
    
    public void setVeiEmpId(Integer veiEmpId) {
        this.veiEmpId = veiEmpId;
    }
    public Integer getVeiPesId() {
        return this.veiPesId;
    }
    
    public void setVeiPesId(Integer veiPesId) {
        this.veiPesId = veiPesId;
    }
    public Set getTbVendaSers() {
        return this.tbVendaSers;
    }
    
    public void setTbVendaSers(Set tbVendaSers) {
        this.tbVendaSers = tbVendaSers;
    }




}


